### ISSUE TITLE
Language en won't generate properly & error when we do `sh <script_name_with_extension>`

### ISSUE THREAD

**Issue by MotikaCraft-TheJoshua** [GIGABAIT-Official/TBungeeUtills#1]
error log for not generating `en` language file
```
[15:24:12] [main/INFO]: Error load configuration files.
[15:24:12] [main/ERROR]: java.io.FileNotFoundException: plugins/TBungeeUtils/language/en.yml (No such file or directory)
[15:24:12] [main/ERROR]: 	at java.base/java.io.FileInputStream.open0(Native Method)
[15:24:12] [main/ERROR]: 	at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
[15:24:12] [main/ERROR]: 	at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
[15:24:12] [main/ERROR]: 	at net.md_5.bungee.config.YamlConfiguration.load(YamlConfiguration.java:77)
[15:24:12] [main/ERROR]: 	at net.md_5.bungee.config.YamlConfiguration.load(YamlConfiguration.java:71)
[15:24:12] [main/ERROR]: 	at bungee.main.Language.<init>(Language.java:42)
[15:24:12] [main/ERROR]: 	at bungee.main.Main.loadConfig(Main.java:76)
[15:24:12] [main/ERROR]: 	at bungee.main.Main.onEnable(Main.java:35)
[15:24:12] [main/ERROR]: 	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:356)
[15:24:12] [main/ERROR]: 	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:320)
[15:24:12] [main/ERROR]: 	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:54)
[15:24:12] [main/ERROR]: 	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
```

**Comment by PadowYT2** [comment]
As of right now, upload it
